# Generated by Django 6.1.1 on 2026-09-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='vehicles/brands/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'vehicle_brands',
                'ordering': ['name'],
            },
        ),
    ]
