# Generated by Django 6.1.1 on 2026-09-05 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/models/')),
                ('is_active', models.BooleanField(default=True)),
                ('vehicle_brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='vehicles.vehiclebrand')),
            ],
            options={
                'db_table': 'vehicle_models',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('vehicle_brand', 'name'), name='unique_vehicle_model_per_brand')],
            },
        ),
    ]
