# Generated by Django 6.1.1 on 2026-09-05 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehiclemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('engine_cc', models.PositiveIntegerField(blank=True, null=True)),
                ('fuel_type', models.CharField(choices=[('PETROL', 'Petrol'), ('ELECTRIC', 'Electric'), ('CNG', 'CNG')], default='PETROL', max_length=20)),
                ('transmission', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATIC', 'Automatic')], default='MANUAL', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/variants/')),
                ('is_active', models.BooleanField(default=True)),
                ('vehicle_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='vehicles.vehiclemodel')),
            ],
            options={
                'db_table': 'vehicle_variants',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('vehicle_model', 'name'), name='unique_vehicle_variant_per_model')],
            },
        ),
    ]
