# Generated by Django 6.1.1 on 2026-09-05 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehiclevariant'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('vehicle_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='years', to='vehicles.vehiclevariant')),
            ],
            options={
                'db_table': 'vehicle_years',
                'ordering': ['year'],
                'constraints': [models.UniqueConstraint(fields=('vehicle_variant', 'year'), name='unique_vehicle_year_per_variant')],
            },
        ),
    ]
