# Generated by Django 6.1.1 on 2026-09-05 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_product_productimage_productcompatibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application_scope', models.CharField(choices=[('ALL_PRODUCTS', 'All Products'), ('SELECTED_PRODUCTS', 'Selected Products'), ('EXCLUDE_PRODUCTS', 'Exclude Products')], max_length=30)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED_AMOUNT', 'Fixed Amount')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('priority', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discounts', to='vehicles.productcategory')),
            ],
            options={
                'db_table': 'category_discounts',
                'ordering': ['priority', '-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('discount_value__gt', 0)), name='discount_value_positive'), models.CheckConstraint(condition=models.Q(('min_order_amount__gte', 0)), name='min_order_amount_non_negative'), models.CheckConstraint(condition=models.Q(('max_discount_amount__isnull', True), ('max_discount_amount__gte', 0), _connector='OR'), name='max_discount_non_negative'), models.CheckConstraint(condition=models.Q(('start_at__lt', models.F('end_at'))), name='discount_start_before_end')],
            },
        ),
    ]
