# Generated by Django 6.1.1 on 2026-09-05 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_categorydiscount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDiscountProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_mappings', to='vehicles.categorydiscount')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_mappings', to='vehicles.product')),
            ],
            options={
                'db_table': 'category_discount_products',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('category_discount', 'product'), name='unique_category_discount_product')],
            },
        ),
    ]
