# Generated by Django 6.1.1 on 2026-09-10 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0010_product_is_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcompatibility',
            options={'ordering': ['vehicle_brand', 'vehicle_model', 'vehicle_variant', 'vehicle_year']},
        ),
        migrations.RemoveConstraint(
            model_name='productcompatibility',
            name='unique_product_vehicle_year',
        ),
        migrations.AddField(
            model_name='productcompatibility',
            name='vehicle_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_compatibilities', to='vehicles.vehiclebrand'),
        ),
        migrations.AddField(
            model_name='productcompatibility',
            name='vehicle_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_compatibilities', to='vehicles.vehiclemodel'),
        ),
        migrations.AddField(
            model_name='productcompatibility',
            name='vehicle_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_compatibilities', to='vehicles.vehiclevariant'),
        ),
        migrations.AlterField(
            model_name='productcompatibility',
            name='vehicle_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_compatibilities', to='vehicles.vehicleyear'),
        ),
        migrations.AddConstraint(
            model_name='productcompatibility',
            constraint=models.UniqueConstraint(condition=models.Q(('vehicle_model__isnull', True), ('vehicle_variant__isnull', True), ('vehicle_year__isnull', True)), fields=('product', 'vehicle_brand'), name='unique_product_vehicle_brand'),
        ),
        migrations.AddConstraint(
            model_name='productcompatibility',
            constraint=models.UniqueConstraint(condition=models.Q(('vehicle_variant__isnull', True), ('vehicle_year__isnull', True)), fields=('product', 'vehicle_model'), name='unique_product_vehicle_model'),
        ),
        migrations.AddConstraint(
            model_name='productcompatibility',
            constraint=models.UniqueConstraint(condition=models.Q(('vehicle_year__isnull', True)), fields=('product', 'vehicle_variant'), name='unique_product_vehicle_variant'),
        ),
        migrations.AddConstraint(
            model_name='productcompatibility',
            constraint=models.UniqueConstraint(condition=models.Q(('vehicle_year__isnull', False)), fields=('product', 'vehicle_year'), name='unique_product_vehicle_year'),
        ),
    ]
