# Generated by Django 6.1.1 on 2026-09-20 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitem_product'),
        ('vehicles', '0011_alter_productcompatibility_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='categorydiscount',
            name='discount_value_positive',
        ),
        migrations.RemoveConstraint(
            model_name='categorydiscount',
            name='min_order_amount_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='categorydiscount',
            name='max_discount_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='categorydiscount',
            name='discount_start_before_end',
        ),
        migrations.RemoveConstraint(
            model_name='categorydiscountproduct',
            name='unique_category_discount_product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_category',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.RemoveConstraint(
            model_name='productcompatibility',
            name='unique_product_vehicle_brand',
        ),
        migrations.RemoveConstraint(
            model_name='productcompatibility',
            name='unique_product_vehicle_model',
        ),
        migrations.RemoveConstraint(
            model_name='productcompatibility',
            name='unique_product_vehicle_variant',
        ),
        migrations.RemoveConstraint(
            model_name='productcompatibility',
            name='unique_product_vehicle_year',
        ),
        migrations.RemoveField(
            model_name='categorydiscount',
            name='product_category',
        ),
        migrations.RemoveField(
            model_name='categorydiscountproduct',
            name='category_discount',
        ),
        migrations.RemoveField(
            model_name='categorydiscountproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductBrand',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.RemoveField(
            model_name='productcompatibility',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productcompatibility',
            name='vehicle_brand',
        ),
        migrations.RemoveField(
            model_name='productcompatibility',
            name='vehicle_model',
        ),
        migrations.RemoveField(
            model_name='productcompatibility',
            name='vehicle_variant',
        ),
        migrations.RemoveField(
            model_name='productcompatibility',
            name='vehicle_year',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
        migrations.DeleteModel(
            name='CategoryDiscount',
        ),
        migrations.DeleteModel(
            name='CategoryDiscountProduct',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductCompatibility',
        ),
    ]
