# Generated by Django 6.1.1 on 2026-09-20 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0011_alter_productcompatibility_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='products/brands/')),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'product_brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/categories/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'product_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('product_brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.productbrand')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.productcategory')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CategoryDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application_scope', models.CharField(choices=[('ALL_PRODUCTS', 'All Products'), ('SELECTED_PRODUCTS', 'Selected Products'), ('EXCLUDE_PRODUCTS', 'Exclude Products')], max_length=30)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED_AMOUNT', 'Fixed Amount')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('priority', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discounts', to='products.productcategory')),
            ],
            options={
                'db_table': 'category_discounts',
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCompatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilities', to='products.product')),
                ('vehicle_brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_compatibilities', to='vehicles.vehiclebrand')),
                ('vehicle_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_compatibilities', to='vehicles.vehiclemodel')),
                ('vehicle_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_compatibilities', to='vehicles.vehiclevariant')),
                ('vehicle_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_compatibilities', to='vehicles.vehicleyear')),
            ],
            options={
                'db_table': 'product_compatibilities',
                'ordering': ['vehicle_brand', 'vehicle_model', 'vehicle_variant', 'vehicle_year'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='products/images/')),
                ('public_id', models.CharField(blank=True, default='', max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'db_table': 'product_images',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CategoryDiscountProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_mappings', to='products.categorydiscount')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_mappings', to='products.product')),
            ],
            options={
                'db_table': 'category_discount_products',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('category_discount', 'product'), name='unique_category_discount_product')],
            },
        ),
        migrations.AddConstraint(
            model_name='categorydiscount',
            constraint=models.CheckConstraint(condition=models.Q(('discount_value__gt', 0)), name='discount_value_positive'),
        ),
        migrations.AddConstraint(
            model_name='categorydiscount',
            constraint=models.CheckConstraint(condition=models.Q(('min_order_amount__gte', 0)), name='min_order_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='categorydiscount',
            constraint=models.CheckConstraint(condition=models.Q(('max_discount_amount__isnull', True), ('max_discount_amount__gte', 0), _connector='OR'), name='max_discount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='categorydiscount',
            constraint=models.CheckConstraint(condition=models.Q(('start_at__lt', models.F('end_at'))), name='discount_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='productcompatibility',
            constraint=models.UniqueConstraint(condition=models.Q(('vehicle_model__isnull', True), ('vehicle_variant__isnull', True), ('vehicle_year__isnull', True)), fields=('product', 'vehicle_brand'), name='unique_product_vehicle_brand'),
        ),
        migrations.AddConstraint(
            model_name='productcompatibility',
            constraint=models.UniqueConstraint(condition=models.Q(('vehicle_variant__isnull', True), ('vehicle_year__isnull', True)), fields=('product', 'vehicle_model'), name='unique_product_vehicle_model'),
        ),
        migrations.AddConstraint(
            model_name='productcompatibility',
            constraint=models.UniqueConstraint(condition=models.Q(('vehicle_year__isnull', True)), fields=('product', 'vehicle_variant'), name='unique_product_vehicle_variant'),
        ),
        migrations.AddConstraint(
            model_name='productcompatibility',
            constraint=models.UniqueConstraint(condition=models.Q(('vehicle_year__isnull', False)), fields=('product', 'vehicle_year'), name='unique_product_vehicle_year'),
        ),
    ]
